### ISSUE TITLE
is the global_name in the initialize right?

### ISSUE THREAD

**Issue by vpereira** [mrkamel/bbqueue-redis#1]
I'm getting an exception here, It looks like it is a typo, no?

https://github.com/mrkamel/bbqueue-redis/blob/b3325df269c373a311a221bcb35f56e0dfabd1a9/lib/bbqueue/consumer.rb#L45

**Comment by mrkamel** [comment]
no typo. `global_name` is required using redis, such that every consumer process gets a globally unique name (i suggest to use something like: `"#{worker_name}_#{hostname}_#{worker_index}"` to have a global per-consumer "currently processing" job list, which is used for cleanup/re-queue in case of consumer crashes or similar.

however, this repo is deprecated (btw. i never released a gem for it).
i'm actively working on https://github.com/mrkamel/bbque instead,
which has nice extra features, like job priorities, job limits, jobs with delay (via schedulers) and i'm already using it in production.

**Comment by vpereira** [comment]
Hey, 
I however prefer to stick with redis because it's already being deployed in my environment and I don't want to add a new component to my stack. I ended up rolling out my own queue system. Thank you!

**Comment by mrkamel** [comment]
`bbque` is redis based as well.
Only `bbqueue` is based on beanstalkd.
